[package]
name = "physics-and-tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
log = "0.4.20"
rand = "*"
rayon = "1.8.0"
